// apps/perf-qwik-rust/frontend/src/routes/login/index.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import { Link, useNavigate, type DocumentHead } from "@builder.io/qwik-city";
import { Button, Input, Label } from "~/components/ui";
import { loginRequest, setTokens } from "~/lib/auth";

export default component$(() => {
  const nav = useNavigate();
  const email = useSignal("dev@example.com");
  const password = useSignal("devpass");
  const error = useSignal("");
  const busy = useSignal(false);

  const onSubmit = $(async () => {
    error.value = "";
    busy.value = true;
    try {
      const res = await loginRequest(email.value, password.value);
      setTokens(res.token, res.refresh_token ?? "");
      await nav("/app/");
    } catch (e) {
      error.value = e instanceof Error ? e.message : String(e);
    } finally {
      busy.value = false;
    }
  });

  return (
    <div class="flex min-h-[60vh] items-center justify-center px-4 py-8">
      <div class="w-full max-w-md rounded-lg border border-border bg-card p-6 text-card-foreground shadow-md">
        <h1 class="mt-0 text-xl font-semibold tracking-tight">ログイン</h1>
        {error.value ? (
          <div
            class="mt-3 rounded-md border border-alert/40 bg-alert/10 px-3 py-2 text-sm text-alert"
            role="alert"
          >
            {error.value}
          </div>
        ) : null}
        <form
          preventdefault:submit
          onSubmit$={onSubmit}
          class="mt-4 flex flex-col gap-4"
        >
          <div class="flex flex-col gap-2">
            <Label for="email">メール</Label>
            <Input
              id="email"
              type="email"
              autoComplete="username"
              bind:value={email}
            />
          </div>
          <div class="flex flex-col gap-2">
            <Label for="pw">パスワード</Label>
            <Input
              id="pw"
              type="password"
              autoComplete="current-password"
              bind:value={password}
            />
          </div>
          <Button type="submit" disabled={busy.value}>
            {busy.value ? "送信中…" : "ログイン"}
          </Button>
        </form>
        <p class="mt-4 text-sm text-muted-foreground">
          <Link href="/" class="text-primary underline-offset-4 hover:underline">
            トップへ
          </Link>
        </p>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "ログイン | perf-qwik-rust",
};

// apps/lean-next-hono/src/app/login/page.tsx
"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { getCsrfToken, signIn } from "next-auth/react";
import { Suspense, useEffect, useState } from "react";

import { persistTokens } from "@/lib/auth-fetch";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

function LoginForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const callbackUrl = searchParams.get("callbackUrl") ?? "/app";

  const [email, setEmail] = useState("dev@example.com");
  const [password, setPassword] = useState("devpass");
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  /** Auth.js の二重送信クッキーを先に付与（マウント直後の signIn で MissingCSRF になるのを防ぐ） */
  useEffect(() => {
    void getCsrfToken();
  }, []);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setPending(true);
    try {
      const loginRes = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });
      if (!loginRes.ok) {
        setError("メールまたはパスワードが正しくありません。");
        return;
      }
      const tokens = (await loginRes.json()) as {
        token: string;
        refresh_token: string;
        expires_in: number;
      };
      persistTokens(tokens);

      const res = await signIn("credentials", {
        email,
        password,
        redirect: false,
      });
      if (res?.error) {
        setError("セッションの確立に失敗しました。再度お試しください。");
        return;
      }
      router.push(callbackUrl);
      router.refresh();
    } finally {
      setPending(false);
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center p-6">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>ログイン</CardTitle>
          <CardDescription>
            まず <code className="text-xs">POST /api/auth/login</code> で
            Access/Refresh を取得し localStorage に保存します。続けて Auth.js
            セッションも確立します（保護 API は Bearer 優先・Cookie
            フォールバック）。開発ユーザー:{" "}
            <code className="text-xs">npm run db:seed</code> 後{" "}
            <code className="text-xs">dev@example.com</code> /{" "}
            <code className="text-xs">devpass</code>
          </CardDescription>
        </CardHeader>
        <form onSubmit={onSubmit}>
          <CardContent className="space-y-4">
            {error ? (
              <p className="text-sm text-destructive" role="alert">
                {error}
              </p>
            ) : null}
            <div className="space-y-2">
              <Label htmlFor="email">メール</Label>
              <Input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">パスワード</Label>
              <Input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full" disabled={pending}>
              {pending ? "送信中…" : "ログイン"}
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-screen items-center justify-center text-sm text-muted-foreground">
          読み込み中…
        </div>
      }
    >
      <LoginForm />
    </Suspense>
  );
}
